# Blackbox exporter modules used by the blackbox-http scrape job.
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [200]
      preferred_ip_protocol: ip4
      follow_redirects: false
      fail_if_ssl: false
